### ISSUE TITLE
[Feature request]: JBIG2 support in pdf

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DanBloomberg/leptonica#102]
```
Can you please implement JBIG2[1] support in pdf?

[1] https://en.wikipedia.org/wiki/JBIG2


```

Original issue reported on code.google.com by `zde...@gmail.com` on 7 Aug 2014 at 7:49

**Comment by jbarlow83** [comment]
There are patent issues.
http://www.archivum.info/comp.compression/2009-07/00024/Re-JBIG2-patents.html

**Comment by amitdo** [comment]
>There are patent issues.
http://www.archivum.info/comp.compression/2009-07/00024/Re-JBIG2-patents.html

The only US patent from this list which hasn't expired yet, is
>US Patent, 6 020 972, Xerox, System for performing collective symbol-based compression of a corpus of documents, Feb. 1, 2000.

filing date is Nov 14, 1997, so it will be  expired in 14 Nov 2017.

**Comment by zdenop** [comment]
Anything new regarding this?

**Comment by zdenop** [comment]
there is [jbig2 encoder]( https://github.com/agl/jbig2enc) based on leptonica ;-) It was created when leptonica does not have pdf export.
Why not to produce pdf with jbig2 directly from leptonica?

**Comment by DanBloomberg** [comment]
Yes, Adam Langley's jbig2enc is indeed based on leptonica.  He built it in
2006, when he was
an intern in the Google Books project.  It's a tribute to his abilities
that he did this in a very short
time period, for many years it was the only open source encoder (it may
still be ...), and it has
required virtually zero maintenance since it was made!  You just don't see
that very often in
the software world.

And yes, it would be nice to include jbig2 compression in leptonica's pdf
generation,
but it's not a high priority.

For jbig2 to work efficiently, the dictionary of bitmaps (of connected
components) should include all components from *many *pages.
This is different from other compression techniques, which compress each
page with no data from other pages.
As  of 2006 there was a flaw in the Adobe implementation of the jbig2
decoder in pdf: the dictionary of
bitmaps was limited to a relatively small number of pages (perhaps ~ 15).
 But it was still big enough
to make using jbig2 worthwhile, compared to g4 tiff.

I don't know the details of the embedding.  If Adobe did something smart
for jbig2 -- like embed the jpeg file
in the pdf (for DCT) and embed jp2k (for JPX), then it shouldn't be hard to
do.  You could then take the
output of jbig2enc and insert the bytes in the pdf file.  The important
thing is not to require having an encoder
and/or decoder library available to do this, because I do not want
leptonica to depend on more libraries.

In any event, let's keep the issue open, and maybe someone will volunteer
to do the heavy lifting.

**Comment by amitdo** [comment]
This issue was opened 6 years ago.

Dan, since you don't seem to have any plan to implement this feature request and nobody else volunteered to do it, maybe it's time to close the issue.

**Comment by DanBloomberg** [comment]
OK, no plan to include jbig2 pdf encoding in leptonica's pdf utilities, so closing.
