### ISSUE TITLE
Support images larger than 2^31 bytes

### ISSUE THREAD

**Issue by jbarlow83** [DanBloomberg/leptonica#138]
In pix1.c line 447 or so, `pixCreateHeader` blocks the opening or creation of images that would take more than 2^31 bytes when decompressed. It seems that this is based on the assumption that size_t is limited to 32-bits, where on most x64 machines it is now a 64-bit quantity.

It's doesn't appear that `struct Pix` has any limitations on size. pixSerializeToMemory does add a 32-bit byte count.

Images created by large format scanners can easily exceed 2^31 bytes (or ~23 sq.ft. for a 400x400 DPI 32-bit color image).

**Comment by DanBloomberg** [comment]
This limit (and other associated ones in the same function, and in some of the *io.c files) are part of a serious effort to make the library secure against input that would otherwise cause an overflow and could be used maliciously.

These limits were imposed based on fuzzing tests.  The library is intended to work on both 32 and 64 bit hardware.  The struct Pix fields are all 32-bit.  the SPix size limits are 1M on dimensions and 400M on total number of pixels; the latter is a max of 1.6GB, which is within the limits imposed in pixCreateHeader().
