### ISSUE TITLE
Improved Document Image Segmentation Algorithm using Multiresolution Morphology

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#219]
Hi Dan,

Are you aware of this paper?
https://www.researchgate.net/publication/221253893_Improved_Document_Image_Segmentation_Algorithm_using_Multiresolution_Morphology

**Comment by DanBloomberg** [comment]
Surprisingly, no  :-)

Surprising because I've known Tom Breuel for years: he and I were
colleagues at Xerox for a while, and later (after a 10 year stint at
Kaiserslautern) at Google.

I'll have a look at it.

**Comment by amitdo** [comment]
Dan, did you read it?

**Comment by DanBloomberg** [comment]
Amit.

Yes.  The page segmentation algorithm in leptonica was meant to be an example of how to do the segmentation quickly using simple morphological operations. It was not meant to be the best and most versatile way to do the segmentation.  For example, it assumes that text lines are horizontal.  Further, with reference to this paper, it was specifically not intended to identify line art,  So really it's a starting point, not a highly tuned production implementation.  Ray Smith has done a much more production-oriented page segmentation in tesseract.

The paper you reference tested using a set of about 100 page images, many or most with drawings, so of course, the example leptonica page segmentation algorithm will not do well on it.

To incorporate line art, some other filters are necessary.  For example, large connected components with thin stroke lines are easily identified and extracted.  See strokes.c, for example.

But I am glad that they used and further publicized the morphological approach.  It has been over 25 years since I published it  :-)

  -- Dan

**Comment by amitdo** [comment]
>But I am glad that they used and further publicized the morphological approach. It has been over 25 years since I published it :-)
:+1:
