### ISSUE TITLE
Fails to find jpeglib.h despite JPEG_INCLUDE_DIR:PATH being set

### ISSUE THREAD

**Issue by rhardih** [DanBloomberg/leptonica#221]
I'm in the process of setting up a cross-compile toolchain, which means I'm looking to explicitly compile each dependency of leptonica.

I'm stumped already on first efforts trying to link a local compiled version of libjpeg:

```bash
fatal error: 'jpeglib.h' file not found #include "jpeglib.h"
```

It seems somewhere the settings for cmake gets lost, even though having manually specified the lib and include paths for libjpeg. Here's a gist of the output of the different steps on the way to compiling, starting from an empty `build` folder:

https://gist.github.com/rhardih/551f9be687aa9f758089e77d70ed0939

**Comment by DanBloomberg** [comment]
Egor, this appears to be a cmake issue.  Do you know why this is happening?

**Comment by amitdo** [comment]
This issue looks similar:
 https://github.com/tesseract-ocr/tesseract/issues/484

**Comment by rhardih** [comment]
CC @egorpugin

**Comment by egorpugin** [comment]
Hi,

Probably I have a nice solution for you (not solution for this ticket).
But first please write how do you want to use leptonica?
Do you want to use leptonica in your app that is compiled e.g. for ios/android (arm)?

**Comment by rhardih** [comment]
Final target will be ARM yes. My usecase is that leptonica is a second second stage dependency of OpenCV through Tesseract, which is why I'm interested in setting up a complete toolchain. Precompiled libs is not an option for me currently.

**Comment by egorpugin** [comment]
Okay. Here what I could suggest.

OpenCV module `text` contains several files. Cmake config `FindTesseract.cmake` to find `tess` is terrible.
If you do not need Erfilter feature or some other Neural Networks stuff, you could take 1 header and 1 source file ocr_tesseract.cpp and put it into your project (app) or even all those files. (I do this in my projects.)

Next step: seems you need tesseract as the end goal, not leptonica. Look at this example https://github.com/cppan/tesseract_example/tree/master/with_cmake which shows you usage of CPPAN (C++ Archive Network) packages (dependencies) manager with cmake integration. You should create `cppan.yml` in your project with the contents from that link. Run `cppan` in dir with `cppan.yml`. Look at `CMakeLists.txt`, add `add_subdirectory(cppan)`, link cppan target to your application `target_link_libraries(main cppan)`.
The advantage of this way that CPPAN includes all your deps (tess,lept,png,jpeg,webp,zlib,...) automatically and inherits all your compiler settings without any work from your side. So, if you build for arm it will inherit your toolchain file etc.


If you don't like this way here are some thoughts about original issue.
The issue is not about leptonica. It's somewhat with cmake, find jpeg module or some other stuff.
1. Try absolute path: `/abs/path/to/jpeg/include` as cmake argument.
2. Look into cmake `Modules/FindJPEG.cmake` somewhere in system (or brew) dir with cmake.

**Comment by rhardih** [comment]
I do actually need the ERFilter, so I'd rather come to a general solution. I think I've come to the conclusion that it's probably a bug in cmake.

Not matter how I try to coerce it to append to it's include paths, it just doesn't work. According to http://www.vtk.org/Wiki/CMake_Cross_Compiling#Searching_and_finding_external_software, just setting `CMAKE_FIND_ROOT_PATH`, should be enough to augment all `FIND_XXX` calls to look there first.

I've also tried explicitly adding the directory and checking it in the bottom of `CmakeLists.txt`:

```cmake
include_directories(/Users/rene/Code/leptonica/dependencies/install/include)

message("INCLUDE_DIRECTORIES: ${INCLUDE_DIRECTORIES}" )

check_include_files(jpeglib.h FOO_JPEG)
```

But as you can see below, even though the documentation says `include_directories` should add to the  `INCLUDE_DIRECTORIES` variable, it doesn't. `jpeglib.h` still isn't picked up:

```bash
-- The C compiler identification is AppleClang 7.3.0.7030029
-- The CXX compiler identification is AppleClang 7.3.0.7030029

<cut for brevity>

-- Using unsigned short
-- Check if the system is big endian - little endian
INCLUDE_DIRECTORIES:
-- Looking for include file jpeglib.h
-- Looking for include file jpeglib.h - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/rene/Code/leptonica/build
```

What I really don't get, is that `find_package(JPEG)`, seems to honor `CMAKE_FIND_ROOT_PATH` just fine and the custom compiled dynamic lib is detected correctly:

```bash
-- Found JPEG: /Users/rene/Code/leptonica/dependencies/install/lib/libjpeg.dylib
```

---

I haven't looked into using `cppan` yet, but if sources for the various deps (tess,lept,png,jpeg...) are just downloaded off the Archive Network and compiled, yet again through cmake, wouldn't I just be back at the same problem once more?

**Comment by egorpugin** [comment]
> wouldn't I just be back at the same problem once more?

No, you don't. If yes, please report, I'll try to investigate.
Packages (in form of source files) from CPPAN come in well-prepared format for compilation and including to user projects with cmake. At the moment windows versions of tesseract and leptonica use `cppan` way as  preffered. Because if not with cppan, you should handle all dependencies yourself once again.

**Comment by rhardih** [comment]
Is there anywhere I can more easily see the transformations done to packages on CPPAN, compared to original source deliveries? The difference between the content of [jpegsrc.v9b.tar.gz](http://www.ijg.org/files/jpegsrc.v9b.tar.gz) and [cppan.tar.gz](https://github.com/cppan-packages/972a155acad9103812e58695a4dfdaed86f23da1c399e86abb6aa4e442ee4f37/raw/master/cppan.tar.gz) seems massive at first glance, (122 files difference/removed) :

```bash
$ diff -Ewbqr jpeg-9b/ cppan/ | wc
     122     488    3608
```

I'm not keen on trusting modified source from a 3rd party, unless I know what's been done. Being able to verify what winds up in used libraries is important.

Being able to inspect the changes done, might also provide the solution here. If the modified versions of leptonica on CPPAN compiles just fine using CMake, with libjpeg as a dependency, I should be able to copy those changes and have it compile just the same locally yes?

**Comment by egorpugin** [comment]
Verifying mechanism is present in some early form. 
To compare and verify packages do the following:
1. https://cppan.org/pvt.cppan.demo.jpeg/version/9.2.0
2. Download the original archive http://www.ijg.org/files/jpegsr9b.zip
3. Unpack it, enter the dir.
4. Create empty cppan.yml
5. Fill it with contents from cppan page from step 1. Save.
6. Run `cppan --prepare-archive .` in that dir.
7. `cppan.tar.gz` will be created in this dir.
8. Download `pvt.cppan.demo.jpeg-9.2.0.tar.gz` archive from that page (it is saved as `cppan.tar.gz`, so don't mix up them).
9. You could check sizes of those archives, check their hashsums. (For some reason at the moment archives is different while packed, so go to step 10.)
10. Unpack first `cppan.tar.gz` into `1` dir.
11. Unpack second `cppan.tar.gz` into `2` dir.
12. Compare them as you wish. On my system they (`1` and `2` dirs) are the same and have total size of `1 381 322`.

CPPAN does not modify files when store it. It just drops all not compiled files.

**Comment by egorpugin** [comment]
By the way on my system
```
$ diff -Ewbqr 1/ 2/
Files 1/cppan.yml and 2/cppan.yml differ
```
`cppan.yml` from server has some statements reordered.

**Comment by rhardih** [comment]
I'll look more into cppan, thanks Egor.

Closing this issue as it is unrelated to leptonica.

For future reference, I did manage to move forward by sidestepping configuration through CMake and just set C_INCLUDE_PATH for  Clang directly. Reference: http://clang.llvm.org/docs/CommandGuide/clang.html.

Export:

```bash
export C_INCLUDE_PATH=/Users/rene/Code/leptonica/dependencies/install/include/
```

My compiler version is AppleClang 7.3.0.
