### ISSUE TITLE
Read Exif tags

### ISSUE THREAD

**Issue by uasan** [DanBloomberg/leptonica#251]
How to read Exif tags from JPEG file?

**Comment by DanBloomberg** [comment]
This is not implemented.  Do you have somethng that you can contribute?

**Comment by uasan** [comment]
I'm not C developer, can only help with testing.

**Comment by Dan9er** [comment]
**EXIF implementation is more important than you think.**

For example, orientation. If you take a picture in a non-native orientation for the CCD, some cameras don't bother rotating the raw image. They just modify the Orientation value in EXIF and make the image viewer deal with it. You can check this value on an image by installing ExifTool (via APT) and running `exiftool -Orientation -n image.jpg`. (This will give you the raw number value found in the data, for a human-readable output remove the `-n`.)

The problem here is that Leptonica currently completely ignores EXIF. In my example, it effectively assumes the Orientation value is 1 (don't rotate raw image). This is a BIG problem because if this value was set to other than 1, the image Leptonica processes ends up rotated. Which is wrong.

I found this bug while working on Tesseract 3 (a HUGE dependant on Leptonica and you know this).  
I noticed when I told Tesseract to also output the TIFF file that "pre-processing" (\*cough\* Leptonica) makes, my vertical JPEG images were *always* getting rotated. This is a big problem for OCR since text ends up sideways (there are ways to circumvent this, namely Tesseract's OSD algorithm, but it takes extra CPU time and is far from perfect). After much asking for help (tesseract-ocr/tesseract#1165) and digging, someone told me that this is a Leptonica issue. Now seeing @uasan having the same concerns as me, I knew I have found the source of the problem.

**Comment by amitdo** [comment]
https://keyj.emphy.de/exif-orientation-rant/
https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

**Comment by DanBloomberg** [comment]
As you can see, the exif rotation flag is a huge swamp.

I consider the best ways around this are (1) to preprocess with an
application that rotates the images according to the tag, or (2) to let
tesseract identify the text orientation, which I believe mostly works
properly.

For roman text, you can also use leptonica to decide the proper orientation
of the text (0, 90, 180, 270) degrees.
See prog/flipdetect_reg.c.

If there is interest, I can build a program that will accept an image and a
confidence threshold and do the rotation if necessary.
This is very fast.

**Comment by uasan** [comment]
I just using another software, 
https://github.com/jcupitt/libvips

Sorry leptonica.

**Comment by DanBloomberg** [comment]
No problem.  Thanks for bringing the issue to my attention.

Best of luck.

**Comment by Dan9er** [comment]
ImageMagick's `convert -auto-orient` tool did the trick ([thanks Mark Setchell](https://stackoverflow.com/questions/46962544/how-to-convert-a-jpeg-to-a-jpeg-with-exif-orientation-1)):
```
$ exiftool -Orientation image.jpg
Orientation                     : Rotate 90 CW
$ exiftool -Orientation -n image.jpg
Orientation                     : 6
$ convert image.jpg -auto-orient result.jpg
$ exiftool -Orientation result.jpg
Orientation                     : Horizontal (normal)
$ exiftool -Orientation -n result.jpg
Orientation                     : 1
```
The two images *look* exactly the same, but the EXIF value was changed to 1. Perfect!

Now, is there any way this can be implemented into Leptonica?

**Comment by DanBloomberg** [comment]
In the digital world almost anything _can_ be done.  The question is _should_ it be done, and I believe the answer is no, for reasons discussed above in this thread.

My offer to build a program that can be used to rotate a text image based on content for roman text is still on the table.

It seems like you have a good work-around with exiftool and convert.  If you make a shell script I can put in in as a comment in leptonica.

**Comment by Dan9er** [comment]
```bash
#!/bin/bash

# Made by Dan9er for the Leptonica project
# Rights waived using CC0

if [[ -z $(command -v exiftool) || -z $(command -v convert) ]]; then
	echo "Dependencies not installed (1)"
	exit 1
fi

if [[ $# = 0 ]]; then
	echo "File name required (2)"
	exit 2
fi

if [[ ${1: -4} != ".jpg" ]]; then
	echo "File is not a JPEG (3)"
	exit 3
fi

if [[ $(exiftool -s3 -n -Orientation "$1") = 1 ]]; then
	echo "Raw image is already upright (0)"
	exit 0
fi

convert "$1" -auto-orient /tmp/exifResult.jpg

echo "Done (0)"
exit 0

# echo "[WARN] EXIF orientation correction failed, output may be rotated"
```

**Comment by DanBloomberg** [comment]
Thank you.  I'll put this into leptonica within the next few days.

**Comment by DanBloomberg** [comment]
I wrote a high-level function, pixOrientCorrect(), that detects text orientation and, with sufficient confidence, will rotate the image to make the text up-right.  I did not make a program that simply calls this function, but that is trivial to do.

**Comment by Dan9er** [comment]
You basically reinvented the wheel dude... Tesseract already has a OSD method to detect text orientation via OCR. The method I showed you rotates the raw image to the correct orientation specified in the EXIF, which has nothing to do with OCR, neural networks, and "confidence".

**Comment by DanBloomberg** [comment]
Understood.

BTW, this was a wheel that we invented.  See the 1995 paper on document image skew and text orientation, which you can get to from here:  
     http://leptonica.org/recent-pubs.html

This new function gives you a way to ignore the exif (which may be wrong), and still have a good chance of orienting the page properly for OCR.

**Comment by DanBloomberg** [comment]
OK, I've finally incorporated the shell script into flipdetect.c comments.
Sometimes a few days can turn into 2 years ...
