### ISSUE TITLE
autotools vs. cmake - different soname

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#253]
`liblept.so` vs `libleptonica.so`

That's not good...

**Comment by DanBloomberg** [comment]
Assuming that we will continue to use both autotools and cmake, Jeff points out
that it will be a considerable amount of work to change the debian soname (liblept.so).

How much trouble is it to change the cmake soname to agree with this?

**Comment by egorpugin** [comment]
It's easy to change name in cmake.

**Comment by DanBloomberg** [comment]
Will that be sufficient?  i.e.,  without changing the autotools name, which is defined in src/Makefile.am?

**Comment by amitdo** [comment]
Why not in all platforms?

**Comment by egorpugin** [comment]
`leptonica` is more beautiful than `lept`.
To keep compatibility on linux we'll rename to `lept` in cmake, but keep `leptonica` on win.
Or even keep it `leptonica`. Why to change? People do not use cmake build for creating debian packages.
And cmake users can live with `libleptonica`.

**Comment by amitdo** [comment]
Many people, on all platforms, build Leptonica and Tesseract from source.

https://github.com/tesseract-ocr/tesseract/issues/957
Here someone build Leptonica using CMake and Tesseract using autotools.

**Comment by zdenop** [comment]
I prefer compatibility before beauty ;-)

**Comment by DanBloomberg** [comment]
@jbreiden

**Comment by jbreiden** [comment]
zdenko is 100% right. We have enough chaos and confusion in life. Leptonica gets exactly one name for its library, and the author (Dan Bloomberg) gets to choose it, and he is chose liblept.so long ago. We stick with it because that is what he wants, and also because it has millions of installed users. Modify cmake build to match. Not negotiable.

**Comment by stweil** [comment]
As long as other packages use `pkg-config` to get the library name, the name does not matter at all (assumed that `lept.pc` is correct). Currently `cmake` creates a broken `lept.pc` file which includes `Libs: -L${libdir} -lleptonica_OUTPUT_NAME-NOTFOUND`. Of course that does not work.

**Comment by egorpugin** [comment]
Wait, wait. Who uses that cmake build?
Package maintainers keep using autotools? Well then, cmake won't touch their stuff.
People who use cmake+autotools build? It's crazy. Just don't do this. Don't mix them.
(Why people use cmake? Because it's simpler.)

Cmake was a reference implementation with some caveats like this one. It worked well for cmake+cmake (tess) builds on windows <- for which it was created. And it is known that it's not 100% conforming to autotools. Different namings, missing pkg-config generator and many other small things.

If you're going to make it 100% "official" - there's some stuff to do (including this ticket change) - and I'll ask you about dropping autotools.

**Comment by DanBloomberg** [comment]
Just to clarify my opinion on this soname business -- I don't have one.  Whatever works, does not cause undue confusion, and requires a minimum of effort and maintenance.

I see no basic problem with Egor's restriction that you build both leptonica and tesseract either with autotools or with cmake, but you don't mix them.  If, with that restriction, it works having two different leptonica sonames, so be it.

**Comment by stweil** [comment]
I agree. There is no urgent need to change the build procedures. For the future, `cmake` could be changed to use the same library name as autotools (liblept instead of libleptonica), and the generated file `lept.pc` could be fixed.

**Comment by xsacha** [comment]
Just to throw my opinion in here:
I am trying to use Leptonica in Hunter so that I can add Leptonica+Tesseract to a CMake project and compile it on all platforms (personally: Windows, Linux, macOS, iOS, Android) with the same CMake.

Just move to a target name for CMake (like Leptonica::leptonica) and keep it consistent for all platforms and I will be happy.
See: https://github.com/xsacha/leptonica/commit/fc164a0709d40d8791896354ee6c4a927ed9a0af#diff-95e351a3805a1dafa85bf20b81d086e6R60

**Comment by egorpugin** [comment]
> I am trying to use Leptonica in Hunter

We are doing the same but with C++ Archive Network https://cppan.org/ and without CMake configs.

**Comment by amitdo** [comment]
>Currently cmake creates a broken lept.pc file which includes Libs: -L${libdir} -lleptonica_OUTPUT_NAME-NOTFOUND. Of course that does not work.

Has this issue been fixed?

**Comment by egorpugin** [comment]
It seems no, as  linux users use only autotools builds.
