### ISSUE TITLE
how to do table detect and cell restruction?

### ISSUE THREAD

**Issue by gds101054108** [DanBloomberg/leptonica#364]
I have some  document image which contains tables , I want to document layout and recovery,I can detect table but I don't know how to do cell restruction,please help me!

**Comment by DanBloomberg** [comment]
Table detection and reconstruction (analysis) is a big, difficult problem, which is why you will see so many papers on the subject.  The primary difficulty is the lack of standardization.  If you can detect tables, you're well ahead of the game.  If you have something that you believe is a table, I'd suggest first looking for lines to help delineate the rows and columns, and then do a word finding operation on the result with the lines removed.  Then look for alignment of the "words" vertically and horizontally.

**Comment by gds101054108** [comment]
@DanBloomberg Thank you very much for your reply! If you have some good solutions one day, please let me know .
