### ISSUE TITLE
Comments wrong

### ISSUE THREAD

**Issue by Phreak87** [DanBloomberg/leptonica#373]
For most 32toX and other pix convert functions the comment is for 1-16 or 32 bpp but works for 24 too.
My project https://github.com/Phreak87/LeptonicaSharp writes Bpp checks from this comments. 

Can you please change this?

**Comment by Phreak87** [comment]
Check this: https://github.com/Phreak87/LeptonicaSharp/issues/2

**Comment by DanBloomberg** [comment]
Can you be a little more explicit?  There is very little support of 24 bpp data for pix in leptonica.  What comment would you like changed, and can you suggest the change?

The issue can be confusing, since most color images are rgb, with 8 bps, so one might naturally consider them as 24 bits/pixel.  But the pixel depth in the pix is almost always 32 bits.  We use the same storage for raster images with rgb and rgba (with rgb, we just ignore the 8 bits of the alpha component.)

**Comment by Phreak87** [comment]
thank you,

is it also possible to export as 24Bpp in pixWriteMemBmp too?
this would be great. My Wrapper gets the data only from this 
Function and stop working with a memory exception if i try to 
access a 24Bpp image. From the comment side the function excepts
24Bpp, so this is no issue - this would be only a enhancement.

**Comment by DanBloomberg** [comment]
Probably not going to happen for bmp.  The work-around is to convert
your 24 bpp to 32 bpp before writing out.

pnm is another uncompressed format, and 24 bpp writing is supported.

png supports 24 bpp writing, is also lossless, and gives you some compression as well.

**Comment by Phreak87** [comment]
I was irritadet because the savefile function of the bitmap works this way
and exports a 24 bpp.
My meaning was that the writetomem takes exactly this data and writes it to
memory.
PNM and PNG was tested but the compression takes more time. For working on
each part with this function I decided to use uncompressed data.
Maybe I use PNG explicit for 24 Bpp.

Dan Bloomberg <notifications@github.com> schrieb am Di., 9. Okt. 2018,
00:04:
