### ISSUE TITLE
Feature request: Visual Studio 2019 support.

### ISSUE THREAD

**Issue by tdhintz** [DanBloomberg/leptonica#450]
2019 is not yet supported.

`D:\Petri\41\leptonica\build64>cmake .. -G "Visual Studio 16 2019 Win64" -DCMAKE_INSTALL_PREFIX="F:/win64/" -DCPPAN_BUILD_SHARED_LIBS=0
CMake Error: Could not create named generator Visual Studio 16 2019 Win64`

**Comment by Jertlok** [comment]
Starting from Visual Studio 16 you need to specify the architecture separately.
So, you need to use` -G "Visual Studio 16 2019" -A x64`
where `-A` can either be supplied with:
* `Win32` _for x86_
* `x64`
* _or other architectures supported by this generator._

**Comment by egorpugin** [comment]
Seems that the original issue exists because of old cmake version.
Please, update to the latest and try again.

**Comment by egorpugin** [comment]
To generate VS solution with SW:
1. Download or update sw, add to PATH.
2. Run `sw generate`.
3. Open solution (a link will be provided in cwd).

**Comment by Micke3rd** [comment]
Why do you dont add build files to the repository ? That's the 3rd issue page I see with a question/answer dialoque how to build for windows or VST.

How do you test the build process without such a script ?

**Comment by zdenop** [comment]
leptonica VS build is tested with [appveyor](https://ci.appveyor.com/project/DanBloomberg/leptonica) after each commit.

**Comment by egorpugin** [comment]
@Micke3rd 
CMake generates build files for VS. It's not needed to include and update generated files in repos each time something changes.

**Comment by Micke3rd** [comment]
> leptonica VS build is tested with [appveyor](https://ci.appveyor.com/project/DanBloomberg/leptonica) after each commit.

thank you @zdenop , the job (definition) behind the link is what I meant. plus it delivers artefacts, what I was looking for.

> CMake generates build files for VS.
Hi @egorpugin,
yes, and yes its generated result shouldn't touch the repo. Because that's only the input for the next build step. But both, the CMake call, and the following step, and every todo til the final output is part of the build process. That (executable) build description should be very much part of the repo. Not a 2nd repo, but the leptonica repo, because of the dependency of program code & build code.

In case you have the feeling, that wouldnt fit to your handling, I agree, mainly because of your APPVEYOR job definition. He contains (what he shouldnt) buildServer stuff and the program build knowledge. With the disadvantage that you depend on that job and server to build.
You could solve this by reducing the job content to:
[
git clone -q --branch=master https://github.com/DanBloomberg/leptonica.git C:\projects\leptonica
git checkout -qf c0fb788cb619c395166355895d97fa60d757dc5

call C:\projects\leptonica\buildscript

Collecting artifacts...
Found artifact 'leptonica.zip' matching 'leptonica.zip' path
Uploading artifacts...
Updating build cache...
Cache 'c:\Users\appveyor\.sw' - Up to date
Build success
]

content of the _buildscript_ should be anything you need to create the artefacts, inclusive the step "Discovering tests". And _buildscript_ should be part of the repo, instead of a not executable leptonica/README.html.
