### ISSUE TITLE
Error in pixReadFromTiffStream: invalid tiffbpl.

### ISSUE THREAD

**Issue by tdhintz** [DanBloomberg/leptonica#522]
The current development version 1.80.0 of Leptonica

 can't read the attached image.  The image was created by LeadTools v19 libraries. This worked in version 1.74.1.

[Untitled.zip](https://github.com/DanBloomberg/leptonica/files/4755117/Untitled.zip)

The error received from pixRead(filename) is:

```
Error in pixReadFromTiffStream: invalid tiffbpl: tiffbpl = 3825, bps = 8, spp = 3, w = 2550
Error in pixReadStream: tiff: no pix returned
Error in pixRead: pix not read
```

**Comment by tdhintz** [comment]
I replaced the sample TIFF with another to avoid possible copyright problem.

**Comment by DanBloomberg** [comment]
Thank you for this report.  While making the image readers more robust to fuzzing, for tiff I added a constraint that you can see this in line 558 of tiffio.c.

For some reason, for your images TIFFScanlineSize() returns 2085, which is exactly 1/2 of what I calculate to hold a full raster line.  Your other example also has the same condition.  I haven't seen this in other tiff files.  I guess this is a valid condition, because if I remove that check it decompresses the file properly.

Do you know anything about the tiff line buffer?  I will alter the check to allow for a half-size buffer.

Dan

**Comment by tdhintz** [comment]
I'm not an expert in this particular kind of TIFF, but LeadTools has been a popular image management library in the past.

**Comment by DanBloomberg** [comment]
We used to support the old jpeg format in tiff for 8 bpp only, and that had the same half-size tiff line buffer.  Fixed.
