### ISSUE TITLE
[win & VS] error LNK2019: unresolved external symbol LeptMsgSeverity referenced in function main

### ISSUE THREAD

**Issue by zdenop** [DanBloomberg/leptonica#575]
I am not sure if I do something wrong but when I tried to compile e.g. pixafileinfo with:

`cl /Fe pixafileinfo.c /If:\win64\include\leptonica /link /LIBPATH:f:/win64/lib leptonica-1.81.0.lib /machine:x64`

I got error:

Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29914 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

```
pixafileinfo.c
Microsoft (R) Incremental Linker Version 14.28.29914.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:pixafileinfo.exe
/LIBPATH:f:/win64/lib
leptonica-1.81.0.lib
/machine:x64
pixafileinfo.obj
pixafileinfo.obj : error LNK2019: unresolved external symbol LeptMsgSeverity referenced in function main
pixafileinfo.exe : fatal error LNK1120: 1 unresolved externals
```

If I replace `return ERROR_INT(...)` with 
```
    fprintf(stderr,... );
    return 1;
```

Compilation is successful and program (pixafileinfo.exe)  works.

I use the latest leptonica build with cmake and command:
```
cmake -Bbuild -DCMAKE_BUILD_TYPE=Release ^
   -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DCMAKE_PREFIX_PATH=%INSTALL_DIR% ^
   -DBUILD_PROG=OFF -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON

cmake --build build --config Release --target install
```

Any idea what could be wrong?

**Comment by DanBloomberg** [comment]
That is very strange.  The global LeptMsgSeverity is defined in utils1.c,
and it is declared and used in ERROR_INT in environ.h.

If you are linking the library, it includes these two files.
Does it matter if the .h file occurs before the library on your compile/link command at the top?

**Comment by DanBloomberg** [comment]
Also, did this only happen for pixafileinfo?

**Comment by DanBloomberg** [comment]
Also, does it give the error when you do static linking instead of shared?

**Comment by zdenop** [comment]
When I build leptonica (AFAIK as static) this way:
`cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DCMAKE_PREFIX_PATH=%INSTALL_DIR% -DSW_BUILD=OFF -DBUILD_PROG=ON`
it works (and it built other leptonica programs).

Also I found out that when I add `LEPT_DLL l_int32  LeptMsgSeverity;` before main function (in pixafileinfo.c) compilation/linking works with also with shared library .

**Comment by zdenop** [comment]
Actually problem for me is not `pixafileinfo.c` build. I tried to build and test one utility on windows that uses leptonica  and its build failed with the same error, so I come back to test build of leptonica program by hand to find reason....

**Comment by zdenop** [comment]
OK. I solved it: adding `/D LIBLEPT_IMPORTS  /TP` made a magic:

`cl /If:\win64\include\leptonica /D LIBLEPT_IMPORTS  /TP pixafileinfo.c  /link /LIBPATH:f:/win64/lib leptonica-1.81.0.lib`

I found it when I look at details why cmake was able to build progs with shared libs ( `-DSW_BUILD=OFF -DBUILD_PROG=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_VERBOSE_MAKEFILE=ON`)

**Comment by DanBloomberg** [comment]
Thank you for solving the problem -- I knew it was above my pay grade.

Do you think something should be added to the build setup or instructions, or are you using a method of building that is non-standard?  (Hint: nobody has reported this problem before you).

**Comment by zdenop** [comment]
I do not know. If somebody builds progs with cmake, there is no problem.
Problem is "only" on windows with VS (or clang-cl), so information in this issue should be sufficient.

**Comment by GitGoliath** [comment]
Adding comment for other developers using only Visual Studio (VS) as building tool (no CMake or command line).

I had same issue building from new VS and including code from skewtest.c and using leptonica-1.84.0d.lib in a test program I made.

Adding LIBLEPT_IMPORTS to preprocessor directive in my program was helpful, it resolve the LeptMsgSeverity not found.

But the other issues afterward were the missing functions for all the functions from Leptonica. The use of /TP is good advice too, as above example is using command line for "cl", it can be confusing as VS does not permit to add file after /TP option enable in GUI. So for those, that use GUI, activate the /TP option on the Leptonica project since it is the leptonica-1.84.0d.lib that need to be C++ compatible when imported from a C++ project. This resolve my missing function in linker step as now the function were C++ named.

Hope this help other.

**Comment by GitGoliath** [comment]
It could help other, so even if this is an old subject.

Found an easier solution, only add:

extern "C" int LeptMsgSeverity;

into your program. No /TP or  LIBLEPT_IMPORTS

**Comment by DanBloomberg** [comment]
l. 489 in environ.h is:

```
LEPT_DLL extern l_int32  LeptMsgSeverity;
```

Every .c source file includes allheaders.h.
allheaders.h includes alltypes.h, which includes environ.h.
So this extern variable is declared in all source files.
Why is the problem happening in VS?

**Comment by GitGoliath** [comment]
It is not that it is extern but that it is "C" type name, my project seems to expect a C++ mangle name. 

From what I got from Co-Pilot, and this could explain why, compiler from VS Studio is more sticky on this:

- In C, functions typically use C-style linkage, meaning function names in the compiled binary are plain and predictable.

- In C++, functions use name mangling due to features like overloading, which adds metadata to symbols for uniqueness. If a library is intended to be used in both C and C++, the extern "C" construct is often employed in C++ code to ensure compatibility with C-style linkage.

Could be a setting in the project, but I started with a pretty much standard one.

**Comment by DanBloomberg** [comment]
So are you suggesting that we write l.489 in environ.h as
```
LEPT_DLL extern "C" l_int32  LeptMsgSeverity;
```
Does that fix your problem with VS?

**Comment by DanBloomberg** [comment]
Yes, I see you are  (looking back)  :-)

OK, I'll prepend the declarations there with
```
extern "C" {
```
there and also for the global variable LeptDebugOK.

**Comment by GitGoliath** [comment]
Hi,

I tried changing Leptonica environ.h and utils1.c but doing that will cause VS to give errors (a lot) when I compile Leptonica projects with Microsoft Visual Studio Community 2022 (64-bit) - Version 17.12.3 . Without any change it compile fine from Git master.

Keep Leptonica project as it is now, I think only my own project need the extern "C" in it for that variable. As it work now when I do that.

**Comment by DanBloomberg** [comment]
Are you saying that the change I just made, to prevent the VS compiler from mangling those variables, does not work with VS? 

Have you tried building from the github master?

**Comment by GitGoliath** [comment]
Ok, I was not having your latest change

Master is building fine in VS 

And I removed the extern "C" from my personal project that was using the Leptonica library and it now compile without issue.  👍

**Comment by DanBloomberg** [comment]
Excellent.  I'm glad this is finally resolved, and I even got to learn something new  :-)

Thank you for following up and doing the testing.
