### ISSUE TITLE
Problem with website leptonica.org?

### ISSUE THREAD

**Issue by terence92** [DanBloomberg/leptonica#643]
Hi, are there any problems with the leptonica website? I can't download leptonica 1.8.2.0 anymore.

**Comment by stweil** [comment]
Yes, it looks like the website is partially down. @DanBloomberg?

Release code can still be downloaded from https://github.com/DanBloomberg/leptonica/releases.

**Comment by DanBloomberg** [comment]
I have a query in to the site maintainer about the web outage.

**Comment by ngmtak56** [comment]
Hi!  What version of leptonica compatible with tesseract 5.2.0?

**Comment by DanBloomberg** [comment]
We're going to get leptonica.org back up on ssl/https.  It will take a couple of days.

**Comment by DanBloomberg** [comment]
The problem seemed to resolve itself, at least for me -- likely from something that happened with the ISP supporting the web site.
However, they are not aware of having changed anything.

Consequently, because it's working properly (as before), we have decided there is no reason to move to a different server that has ssl/https.  Will revisit if the issue comes up again.  Please make sure you can get to leptonica.org and feel free to close the issue if you can.
