### ISSUE TITLE
1.83 release date?

### ISSUE THREAD

**Issue by zdenop** [DanBloomberg/leptonica#656]
Last release (1.82) was done Sep 22, 2021. In meantime there was more then 120 commits. 
When do you plan to release version 1.83?

BTW: [tesseract 5.3](https://groups.google.com/g/tesseract-ocr/c/A22At5a4eDA) should be released soon. Also [libtiff](https://download.osgeo.org/libtiff/?C=M&O=D) is preparing new release (4.5.0)

**Comment by DanBloomberg** [comment]
Funny you mention this.  I've been thinking about doing it, and procrastinating a bit because I have
a couple of small (say, 1 to 3 day) projects to do; namely issues 653 and 597.

1.83 has a couple of things that will make releasing a debian version a bit more difficult (sorry, Jeff):
* raised the major .so number to 6
* renamed autotools generated libraries from liblept to libleptonica, in accord with cmake

I'll make an attempt to release 1.83 by January 10, 2023.

**Comment by DanBloomberg** [comment]
Done.

**Comment by jbreiden** [comment]
Bastian Germann ***@***.***) sponsored Alexander's most recent upload
to Debian, and I think he is also the right person to sponsor the next one.
Please let me know if there is any trouble. Thank you.

**Comment by amitdo** [comment]
@jbreiden,

About your comment. Was it about both Leptonica and Tesseract or just Tesseract?

https://github.com/tesseract-ocr/tesseract/issues/3987

**Comment by jbreiden** [comment]
Just Tesseract. I'll check with Dan about Leptonica 1.83. Last time we
talked he was thinking of renaming the .so, which I am dreading.

**Comment by DanBloomberg** [comment]
And I did up it to 6.0.0.  With profuse apologies.

**Comment by amitdo** [comment]
@jbreiden,

Do you remember my request to package Leptonica 1.83* in Debian Bookworm?

\* 1.83.1 was just released.

**Comment by jbreiden** [comment]
I do remember, but am struggling to keep my head above the water, and it
has not happened. I am sorry. Dan, can we talk this weekend?

**Comment by DanBloomberg** [comment]
Sure.  I'll be around, give me a call.

**Comment by amitdo** [comment]
https://github.com/DanBloomberg/leptonica/issues/663

**Comment by amitdo** [comment]
It seems that the next next release of Debian will officially support Leptonica 1.8**2**.

The next opportunity to package 1.83 (or maybe 1.84) for Debian Testing will come early next year, before the release of Ubuntu 24.04.

**Comment by zffocussss** [comment]
what about 1.83 for Debian packages? the latest one is 1.82.0-3

<img width="1720" alt="image" src="https://user-images.githubusercontent.com/46145695/237030729-cae6ea7f-b8fc-470e-bf7d-de7864d532f3.png">

**Comment by DanBloomberg** [comment]
I'd certainly like to have 1.83 (or likely 1.84) released in time for ubuntu 24.04, which means sometime late in 2023 to be safe.  Jeff has investigated some of the issues that have come up in 1.83 because (1) we changed the name of the library in autotools so that it is the same with all builds on all platforms and (2) we changed the major SO number.
