### ISSUE TITLE
Compression Ratio being lower for JBIG2 than JBIG1 ???!!!

### ISSUE THREAD

**Issue by Sahil-5111998** [DanBloomberg/leptonica#672]
I am currently working on the compression of binary images. There is an algorithm that I am trying to test and **compare its compression ratio to JBIG2 encoded images**.

I am getting into a problem, and I am hoping that you might be able to help me here.
I want to compute the compression ratio of specific images using my algorithm and computer them to standards JBIG1 and JBIG2. For JBIG1, I am using **JBIG-kit (from Markus K)** and **jbig2enc for JBIG2 compression**. However, the size of the encoded **JBIG2 file is similar to that of the JBIG1 (.jbg) encoder**. This should not happen as JBIG2 should give at least 2-3 times smaller results.
I am giving a .pbm image as input for both encoders, and in some cases, the JBIG1 encoder is giving me a lower size.

For generating the jbig2 encoded file I am using the command:
`$ jbig2 -s a.pbm > a.jb2`
The size of this file is coming more as compared to one generated by jbig1 encoder.
As the encoder is using leptonica library, can you please let me know what wrong am I doing here?

**Comment by DanBloomberg** [comment]
I agree that doesn't seem right, but I haven't used the jbig1 kit -- in fact, I didn't even know that jbig1 was in use at all.

Please tell me:
* how you built jbig2enc (and on what platform)
* how you display the resultin g jbig2 file
and send a pair of image files for the same image:e.g., tiff and jbig2

**Comment by DanBloomberg** [comment]
I see that ubuntu has a 'snaps' facility that is similar to the Apple's 'macports' and the debian package manager.
They all download a library along with any dependent libraries that are not found.

You have chosen to test on a particular image that has only 27 connected components when converted to 1 bpp, and all the components are significantly different.  Therefore, jbig2 will compress it losslessly.  But jbig2 is usually used for lossy compression, and that is where it shines.

jbig (aka jbig1) only does lossless compression.  Because your special image is compressed losslessly by jbig2, I'd expect the results to be comparable in size.  But in any event, the big advantage that jbig2 has when it can use lossy compression does not exist for your hand example.

I suggest you make the comparison for some scanned text.

**Comment by Sahil-5111998** [comment]
ok thanks
